name: Auto Jackpot Post

on:
  schedule:
    - cron: '0 16 * * *'   # Jalan setiap hari jam 23:00 WIB
    - cron: '10 16 * * *'  # Jalan setiap hari jam 23:10 WIB
  workflow_dispatch:       # Biar bisa dijalankan manual juga (opsional)

jobs:
  jackpot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 python-dotenv

      - name: Run jackpot script
        env:
          WP_API: ${{ secrets.WP_API }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          WP_PAGE_ID: ${{ secrets.WP_PAGE_ID }}
        run: |
          python run.py
